name: Maven Package

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Bump version
      id: bump
      uses: mickem/gh-action-bump-maven-version@v1

    - name: Test with Maven
      run: mvn test --file pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
